// projects/cefi/src/app/auth/sign-in/sign-in.component.ts
import { Component } from '@angular/core';
import { AuthProvider, GithubAuthProvider, GoogleAuthProvider } from '@angular/fire/auth';
import { Router } from '@angular/router';
import { AuthService } from '../auth.service';

@Component({
  selector: 'app-sign-in',
  templateUrl: './sign-in.component.html',
  styleUrls: ['./sign-in.component.css'],
})
export class SignInComponent {
  email = '';
  password = '';
  processing = false;

  constructor(
    private router: Router,
    private auth: AuthService,
  ) {}

  async signIn(provider: AuthProvider | { email: string; password: string }) {
    this.processing = true;

    try {
      await this.auth.signIn(provider);
      this.router.navigate(['']);
    } catch (e) {
      window.alert('Failed to sign in');
    } finally {
      this.processing = false;
    }
  }

  async signInGoogle() {
    await this.signIn(new GoogleAuthProvider());
  }

  async signInGithub() {
    await this.signIn(new GithubAuthProvider());
  }

  async signInEmail(email: string, password: string) {
    this.signIn({ email, password });
  }
}

<div class="mx-auto px-4 max-w-screen-xl">
  <div class="card bg-base-100 shadow-xl">
    <div class="card-body">
      <h2 class="card-title">Sign In</h2>
      <div class="flex flex-col">
        <button class="btn btn-neutral btn-outline w-full my-2" (click)="signInGoogle()">
          Google
        </button>
        <button class="btn btn-neutral btn-outline w-full my-2" (click)="signInGithub()">
          GitHub
        </button>
      </div>
      <form #formRef="ngForm" (submit)="signInEmail(email, password)">
        <div class="form-control w-full">
          <label class="label">
            <span class="label-text">Email</span>
            <span class="label-text-alt"></span>
          </label>
          <input
            #emailNgModelRef="ngModel"
            type="text"
            placeholder=""
            class="input input-bordered w-full"
            [class]="{
              'input-error': emailNgModelRef.errors && emailNgModelRef.touched
            }"
            required
            [readOnly]="processing"
            autocomplete="email"
            [(ngModel)]="email"
            name="email"
          />
          <label class="label">
            <span class="label-text"></span>
            <span class="label-text-alt"></span>
          </label>
        </div>
        <div class="form-control w-full">
          <label class="label">
            <span class="label-text">Password</span>
            <span class="label-text-alt"></span>
          </label>
          <input
            #passwordNgModelRef="ngModel"
            type="password"
            placeholder=""
            class="input input-bordered w-full"
            [class]="{
              'input-error': passwordNgModelRef.errors && passwordNgModelRef.touched
            }"
            required
            [readOnly]="processing"
            autocomplete="current-password"
            [(ngModel)]="password"
            name="password"
          />
        </div>
        <label class="label">
          <span class="label-text"></span>
          <span class="label-text-alt"></span>
        </label>
        <div class="card-actions justify-end">
          <button class="btn btn-primary" [disabled]="formRef.invalid || processing">
            Sign In
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

// projects/kyc-provider/src/routes/auth/sign-in/+page.svelte
<script lang="ts">
	import { formula } from 'svelte-formula';
	import { authService } from '../../../models/state';
	import { GoogleAuthProvider } from 'firebase/auth';

	let processing = false;
	let email = '';
	let password = '';

	const validators = {};
	const formValidators = {};

	const { touched, validity, isFormValid } = formula({
		validators,
		formValidators
	});

	function signInGoogle() {
		authService.signIn(new GoogleAuthProvider());
	}

	function signInGithub() {}

	function signInEmail() {}
</script>

<div class="card bg-base-100 shadow-xl">
	<div class="card-body">
		<h2 class="card-title">Sign In</h2>
		<div class="flex flex-col">
			<button class="btn btn-neutral btn-outline w-full my-2" on:click={signInGoogle}>
				Google
			</button>
			<button class="btn btn-neutral btn-outline w-full my-2" on:click={signInGithub}>
				GitHub
			</button>
		</div>
		<form on:submit={signInEmail}>
			<div class="form-control w-full">
				<span class="label">
					<span class="label-text">Email</span>
					<span class="label-text-alt" />
				</span>
				<input
					type="text"
					placeholder=""
					class="input input-bordered w-full"
					class:input-error={$touched.email && !$validity.email}
					required
					readonly={processing}
					autocomplete="email"
					bind:value={email}
					name="email"
				/>
				<span class="label">
					<span class="label-text" />
					<span class="label-text-alt" />
				</span>
			</div>
			<div class="form-control w-full">
				<span class="label">
					<span class="label-text">Password</span>
					<span class="label-text-alt" />
				</span>
				<input
					type="password"
					placeholder=""
					class="input input-bordered w-full"
					class:input-error={$touched.password && !$validity.password}
					required
					readonly={processing}
					autocomplete="current-password"
					bind:value={password}
					name="password"
				/>
				<span class="label">
					<span class="label-text" />
					<span class="label-text-alt" />
				</span>
			</div>
			<div class="card-actions justify-end">
				<button class="btn btn-primary" disabled={!$isFormValid || processing}> Sign In </button>
			</div>
		</form>
	</div>
</div>
