// projects/cefi/src/app/auth/sign-out/sign-out.component.ts
import { AuthService } from '../auth.service';
import { Component, OnInit } from '@angular/core';
import { timer } from 'rxjs';

@Component({
  selector: 'app-sign-out',
  templateUrl: './sign-out.component.html',
  styleUrls: ['./sign-out.component.css'],
})
export class SignOutComponent implements OnInit {
  constructor(private auth: AuthService) {}

  ngOnInit() {
    this.auth.signOut().then(() => {
      timer(6000).subscribe(() => {
        window.location.reload();
      });
    });
  }
}

<div class="mx-auto px-4 max-w-screen-xl">
  <div class="card bg-base-100 shadow-xl">
    <div class="card-body">
      <h2 class="card-title">Succeeded To Sign Out</h2>
      <p>Redirecting...</p>
    </div>
  </div>
</div>

// projects/kyc-provider/src/routes/auth/sign-out/+page.svelte
<script lang="ts">
	import { authService } from '../../../models/state';

	authService.signOut().then(() => {
		location.href = '/';
	});
</script>

<div class="card bg-base-100 shadow-xl">
	<div class="card-body">
		<h2 class="card-title">Succeeded To Sign Out</h2>
		<p>Redirecting...</p>
	</div>
</div>
