// projects/yieldaggregator/src/routes/vaults/+page.svelte
<script lang="ts">
  import { formula } from 'svelte-formula';
	import { authService } from '../../../models/state';
	import { GoogleAuthProvider } from 'firebase/auth';

	let processing = false;
  let address = "";
	let vault = {
    id: number,
    name:string
  }

  let keyword = ""

	const validators = {};
	const formValidators = {};

	const { form, touched, validity, isFormValid } = formula({
		validators,
		formValidators
	});

	async function signInGoogle() {
		await authService.signIn(new GoogleAuthProvider());
		location.href = '/';
	}

  function getSymbol(vaultId: number) {
    return ''
  }

  function getSymbolImage(symbol:string ){
    return ''
  }

  function getMinApy(vaultId: number) {
    return 0
  }

  function getMaxApy(vaultId: number) {
    return 0
  }

  function totalDepositedUsdValue(vaultId: number) {
    return 0
  }
</script>

<div class="mx-auto max-w-screen-xl">
  <div class="flex flex-row flex-wrap mb-8">
    <div class="text-xl breadcrumbs">
      <ul>
        <li>Vaults</li>
      </ul>
    </div>
    <span class="flex-auto"></span>
    <div class="flex flex-row gap-2">
      <a class="btn btn-accent btn-outline" href="deposit/{ address }">
        <span class="material-symbols-outlined">monetization_on</span>
        <span>Your Deposits</span>
      </a>
      <a class="btn btn-info btn-outline" href="..">
        <span class="material-symbols-outlined">info</span>
        <span>About</span>
      </a>
    </div>
  </div>

  <div class="flex flex-row flex-wrap items-end mb-8">
    <form use:form on:submit={() => {}}>
      <div class="form-control w-full md:max-w-xs">
        <label class="label">
          <span class="label-text">Filters</span>
        </label>
        <div class="input-group">
          <input
            type="text"
            class="input input-bordered w-full"
            placeholder="ATOM"
            required
            readonly={processing}
            bind:value={keyword}
            name="keyword"
          />
          <button class="btn btn-square" disabled={!$isFormValid || processing}>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              class="h-6 w-6"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
              />
            </svg>
          </button>
        </div>
      </div>
    </form>
  </div>

  <div class="card bg-base-100 shadow-xl mb-8">
    <div class="card-body">
      <h2 class="card-title">Available Vaults</h2>
      <p>Select a vault to deposit funds based on your preferences, and earn yield.</p>
      <div class="overflow-x-auto max-h-96">
        <table class="table w-full">
          <!-- head -->
          <thead>
            <tr>
              <th></th>
              <td>Name</td>
              <td>description</td>
              <td>Asset</td>
              <td>APY</td>
              <td>Commission Rate</td>
              <td>Total Deposited (USD)</td>
            </tr>
          </thead>
          <tbody>
            <ng-container *ngFor="let vault of vaults; let i = index">
              <tr class="hover cursor-pointer" routerLink="{ vault.id }">
                <th>#{ vault.id }</th>
                <div class="dropdown dropdown-hover items-center">
                  <label tabindex="0">
                    <td style="max-width: 10rem" class="truncate">
                      { vault.name }
                    </td>
                  </label>
                  <div
                    tabindex="0"
                    class="dropdown-content z-[1] card card-compact w-96 max-h-48 p-2 shadow bg-base-200 text-primary-content"
                  >
                    <div class="card-body">
                      <h3 class="card-title truncate max-w-full">
                        #{ vault.id } { vault.name }
                      </h3>
                      <p class="truncate">{ vault.description || 'No description' }</p>
                    </div>
                  </div>
                </div>
                <td class="max-w-xs truncate">
                  { vault.description }
                </td>
                <td>
                  <div class="flex items-center space-x-3 gap-2" *ngIf="symbols">
                    <ng-container *ngIf="symbols[i]?.img">
                      <div class="avatar">
                        <div class="mask mask-circle w-6 h-6">
                          <img src="{ getSymbolImage(getSymbol(vault.id))}" alt="Asset Symbol" />
                        </div>
                      </div>
                    </ng-container>
                    <ng-container *ngIf="!symbols[i]?.img">
                      <span class="material-symbols-outlined">question_mark</span>
                    </ng-container>
                    <span>
                      {getSymbol(vault.id)}
                    </span>
                  </div>
                </td>
                <td>
                  <span *ngIf="vaultsInfo?.[i]?.certainty">=</span>
                  <span *ngIf="vaultsInfo?.[i]?.certainty === false">≒</span>
                  <span>{{ getMinApy(vault.id).fixed(2) }}</span>
                  <span *ngIf="vaultsInfo?.[i]?.minApy !== vaultsInfo?.[i]?.maxApy">
                    ~{getMaxApy(vault.id).fixed(2)}
                  </span>
                </td>
                <td>{ vault.withdraw_commission_rate.fixed(2) }</td>
                <td>{ totalDepositedUsdValue(vault.id).fixed(2) }</td>
              </tr>
            </ng-container>
          </tbody>
        </table>
        <p *ngIf="!vaults?.length" class="text-center">There is no vault.</p>
      </div>
    </div>
  </div>

  <div class="card lg:card-side bg-base-100 shadow-xl mb-4">
    <div class="card-body">
      <h2 class="card-title">Vault Creation</h2>
      <P>
        You can become a Vault Creator if you choose to create your own unique vault. Earn
        commission based on strategy popularity.
      </P>
      <ol class="list-decimal ml-4">
        <li>Tailor assets according to your preferences</li>
        <li>Fine-tune your strategy weights</li>
        <li>Set your commission rate</li>
      </ol>
      <div class="card-actions justify-end">
        <button class="btn btn-secondary" routerLink="create">
          <span class="material-symbols-outlined">create</span>
          <span>Create Vault</span>
        </button>
      </div>
    </div>
  </div>
</div>

// projects/portal/src/app/views/interest-rate-swap/vaults/vaults.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'view-vaults',
  templateUrl: './vaults.component.html',
  styleUrls: ['./vaults.component.css'],
})
export class VaultsComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}
}

<div class="bg-[#39465d] min-h-screen">
  <div class="mx-auto max-w-screen-xl w-full p-8">
    <div class="flex flex-row flex-wrap mb-8">
      <div class="text-2xl font-bold breadcrumbs">
        <ul>
          <li>Markets</li>
        </ul>
      </div>
      <span class="flex-auto"></span>
      <div class="join">
        <button class="btn btn-sm btn-primary glass join-item" (click)="changeSimple()">
          Earn
        </button>
        <button class="btn btn-sm btn-accent text-neutral join-item">Trade</button>
      </div>
    </div>

    <p class="font-bold">Exit anytime at market price.</p>
    <!-- <p class="font-light">
      Looking to find more vaults? Check
      <a class="link link-info font-semibold" routerLink="/yield-aggregator/vaults"> Gluon Vaults</a
      >.
    </p> -->

    <div class="flex my-8 gap-4">
      <form>
        <div class="form-control w-full">
          <div class="join">
            <input
              type="text"
              placeholder="Search"
              class="join-item input input-bordered w-full max-w-xs"
            />
            <button class="btn btn-square">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                class="h-6 w-6"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
                />
              </svg>
            </button>
          </div>
        </div>
      </form>
      <span class="flex-auto"></span>
      <!-- <div class="join">
      <button class="btn btn-sm btn-neutral join-item">Active</button>
      <button class="btn btn-sm join-item">Inactive</button>
    </div> -->
      <button
        class="btn btn-sm btn-square"
        [class]="{ 'btn-neutral': viewMode === 'table' }"
        (click)="viewMode = 'table'"
      >
        <span class="material-symbols-outlined">menu</span>
      </button>
      <button
        class="btn btn-sm btn-square"
        [class]="{ 'btn-neutral': viewMode === 'grid' }"
        (click)="viewMode = 'grid'"
      >
        <span class="material-symbols-outlined">grid_view</span>
      </button>
    </div>

    <ng-container *ngIf="tranchePools === null; then loading; else loaded"> </ng-container>
    <ng-template #loading>
      <p class="text-center">
        <span class="loading loading-ring loading-lg"></span>
      </p>
    </ng-template>
    <ng-template #loaded>
      <ng-container *ngIf="(tranchePools?.length || 0) > 0; then exist; else empty"> </ng-container>

      <ng-template #exist>
        <div class="overflow-x-auto" *ngIf="viewMode === 'table'">
          <table class="table">
            <thead>
              <tr class="border-b-2 border-[#adc9ff]">
                <th></th>
                <td>
                  <button class="btn btn-ghost btn-xs flex-nowrap">
                    <span>Name</span>
                    <span
                      class="material-symbols-outlined"
                      [class]="{ 'text-info': sortType === 'name' }"
                    >
                      keyboard_arrow_down
                    </span>
                  </button>
                </td>
                <td>
                  <button class="btn btn-ghost btn-xs flex-nowrap">
                    <span>Maturity</span>
                    <span
                      class="material-symbols-outlined"
                      [class]="{ 'text-info': sortType === 'maturity' }"
                    >
                      keyboard_arrow_down
                    </span>
                  </button>
                </td>
                <td>
                  <button class="btn btn-ghost btn-xs flex-nowrap">
                    <span>Underlying APY</span>
                    <span
                      class="material-symbols-outlined"
                      [class]="{ 'text-info': sortType === 'underlying' }"
                    >
                      keyboard_arrow_down
                    </span>
                  </button>
                </td>
                <!-- <td>
                  <button class="btn btn-ghost btn-xs flex-nowrap">
                    <span>Implied APY</span>
                    <span
                      class="material-symbols-outlined"
                      [class]="{ 'text-info': sortType === 'implied' }"
                    >
                      keyboard_arrow_down
                    </span>
                  </button>
                </td> -->
                <td>
                  <button class="btn btn-ghost btn-xs flex-nowrap">
                    <span>Long Yield APY</span>
                    <span
                      class="material-symbols-outlined"
                      [class]="{ 'text-info': sortType === 'long' }"
                    >
                      keyboard_arrow_down
                    </span>
                  </button>
                </td>
                <td>
                  <button class="btn btn-ghost btn-xs flex-nowrap">
                    <span>Fixed Yield APY</span>
                    <span
                      class="material-symbols-outlined"
                      [class]="{ 'text-info': sortType === 'fixed' }"
                    >
                      keyboard_arrow_down
                    </span>
                  </button>
                </td>
              </tr>
            </thead>
            <tbody>
              <ng-container *ngFor="let pool of tranchePools; let i = index">
                <tr
                  class="hover cursor-pointer border-b-2 border-[#adc9ff]"
                  [routerLink]="[pool.strategy_contract, pool.id]"
                >
                  <th>
                    <div class="avatar">
                      <div class="w-8 rounded-full">
                        <img src="{{ getVaultImage(pool.strategy_contract)?.image }}" />
                      </div>
                      <div class="avatar -ml-2 mt-4">
                        <div class="w-4 rounded-full">
                          <img src="{{ getVaultImage(pool.strategy_contract)?.subImage }}" />
                        </div>
                      </div>
                    </div>
                  </th>
                  <td>
                    <div>
                      <div class="text-xl font-bold">
                        {{ getTranchePoolVault(pool.strategy_contract)?.name }}
                      </div>
                      <div class="text-sm opacity-50"></div>
                    </div>
                  </td>
                  <td>
                    <div>
                      <div class="text-xl font-bold">
                        {{ calcMaturity(pool) | date : 'mediumDate' }}
                      </div>
                      <div class="text-sm opacity-50">{{ calcRestDays(pool) }} days</div>
                    </div>
                  </td>
                  <td>
                    <div>
                      <div class="text-xl font-bold">
                        {{  trancheLongAPYs?.[i]?.ls_apy || 0 | percent : '1.0-2' }}
                      </div>
                      <div class="text-sm opacity-50">
                        {{ trancheTokenPrices?.[i]?.depositPrice || 0 | currency }}
                      </div>
                    </div>
                  </td>
                  <!-- <td>
                    <div class="text-xl font-bold">
                      {{ trancheFixedAPYs?.[i]?.pt_apy || 0 | percent : '1.0-2' }}
                    </div>
                  </td> -->
                  <td>
                    <div
                      class="flex flex-col items-center gap-3 btn btn-primary"
                      [routerLink]="[pool.strategy_contract, pool.id]"
                      [queryParams]="{ view: 'yt' }"
                    >
                      <div class="text-blue-200 text-xl mr-2">YT</div>
                      <div>
                        <div class="text-lg font-bold">
                          {{ trancheLongAPYs?.[i]?.yt_apy || 0 | percent : '1.0-2' }}
                        </div>
                        <div class="text-sm opacity-50">
                          {{ trancheTokenPrices?.[i]?.ytPrice || 0 | currency }}
                        </div>
                      </div>
                    </div>
                  </td>
                  <td>
                    <div
                      class="flex flex-col items-center gap-3 btn btn-accent text-neutral"
                      [routerLink]="[pool.strategy_contract, pool.id]"
                      [queryParams]="{ view: 'pt' }"
                    >
                      <div class="text-green-100 text-xl mr-2">PT</div>
                      <div>
                        <div class="text-lg font-bold">
                          {{ trancheFixedAPYs?.[i]?.pt_apy || 0 | percent : '1.0-2' }}
                        </div>
                        <div class="text-sm opacity-50">
                          {{ trancheTokenPrices?.[i]?.ptPrice || 0 | currency }}
                        </div>
                      </div>
                    </div>
                  </td>
                </tr>
              </ng-container>
            </tbody>
          </table>
        </div>

        <div class="flex flex-row flex-wrap gap-12" *ngIf="viewMode === 'grid'">
          <ng-container *ngFor="let pool of tranchePools; let i = index">
            <div
              style="
                background: linear-gradient(180deg, rgba(53, 75, 116, 0.94) 0.07%, #1f2736 59.52%);
              "
              class="card shadow-xl"
            >
              <div class="card-body">
                <div class="flex items-center gap-3">
                  <div>
                    <h2 class="card-title">
                      {{ getTranchePoolVault(pool.strategy_contract)?.name }}
                    </h2>
                    <div class="text-sm opacity-50"></div>
                  </div>
                  <span class="flex-auto"></span>
                  <div class="avatar">
                    <div class="w-8 rounded-full">
                      <img src="{{ getVaultImage(pool.strategy_contract)?.image }}" />
                    </div>
                    <div class="avatar -ml-2 mt-4">
                      <div class="w-4 rounded-full">
                        <img src="{{ getVaultImage(pool.strategy_contract)?.subImage }}" />
                      </div>
                    </div>
                  </div>
                </div>
                <div class="overflow-x-auto">
                  <table class="table">
                    <tbody>
                      <tr>
                        <td>
                          <div class="text-lg opacity-75">Maturity</div>
                        </td>
                        <td>
                          <div class="text-xl font-bold">
                            {{ calcMaturity(pool) | date : 'mediumDate' }}
                          </div>
                          <div class="text-sm opacity-50">{{ calcRestDays(pool) }} days</div>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <div class="text-lg opacity-75">Underlying APY</div>
                        </td>
                        <td>
                          <div class="text-xl font-bold">
                            {{  trancheLongAPYs?.[i]?.ls_apy || 0 | percent : '1.0-2' }}
                          </div>
                          <div class="text-sm opacity-50">
                            {{ trancheTokenPrices?.[i]?.depositPrice || 0 | currency }}
                          </div>
                        </td>
                      </tr>
                      <!-- <tr>
                        <td>
                          <div class="text-lg opacity-75">Implied APY</div>
                        </td>
                        <td>
                          <div class="text-xl font-bold">
                            {{ trancheFixedAPYs?.[i]?.pt_apy || 0 | percent : '1.0-2' }}
                          </div>
                        </td>
                      </tr> -->
                    </tbody>
                  </table>
                </div>
                <div
                  class="flex gap-3 btn btn-primary justify-start items-center"
                  [routerLink]="[pool.strategy_contract, pool.id]"
                  [queryParams]="{ view: 'yt' }"
                >
                  <div class="text-blue-200 text-xl mr-2">YT</div>
                  <div>
                    <div class="sm:text-xl font-bold">Long Yield APY</div>
                    <div class="text-sm opacity-50">Price</div>
                  </div>
                  <div>
                    <div class="sm:text-xl font-bold">
                      {{ trancheLongAPYs?.[i]?.yt_apy || 0 | percent : '1.0-2' }}
                    </div>
                    <div class="text-sm opacity-50">
                      {{ trancheTokenPrices?.[i]?.ytPrice || 0 | currency }}
                    </div>
                  </div>
                </div>
                <div
                  class="flex gap-3 btn btn-accent text-neutral justify-start items-center"
                  [routerLink]="[pool.strategy_contract, pool.id]"
                  [queryParams]="{ view: 'pt' }"
                >
                  <div class="text-green-100 text-xl mr-2">PT</div>
                  <div>
                    <div class="sm:text-xl font-bold">Fixed Yield APY</div>
                    <div class="text-sm opacity-50">Price</div>
                  </div>
                  <div>
                    <div class="sm:text-xl font-bold">
                      {{ trancheFixedAPYs?.[i]?.pt_apy || 0 | percent : '1.0-2' }}
                    </div>
                    <div class="text-sm opacity-50">
                      {{ trancheTokenPrices?.[i]?.ptPrice || 0 | currency }}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </ng-container>
        </div>
      </ng-template>

      <ng-template #empty>
        <p class="font-bold text-lg text-error">* No vault</p>
      </ng-template>
    </ng-template>
  </div>
</div>
