// projects/portal/src/app/views/nft-pawnshop/borrowers/borrower-nfts/borrower-nft/borrow/borrow.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { BorrowRequest } from 'projects/portal/src/app/models/nft-pawnshops/nft-pawnshop.model';
import { Metadata } from 'projects/shared/src/lib/models/ununifi/query/nft/nft.model';
import {
  ListedNfts200ResponseListingsInner,
  BidderBids200ResponseBidsInner,
  Loans200ResponseLoansInner,
} from 'ununifi-client/esm/openapi';

@Component({
  selector: 'view-borrow',
  templateUrl: './borrow.component.html',
  styleUrls: ['./borrow.component.css'],
})
export class BorrowComponent implements OnInit {
  @Input()
  classID?: string | null;
  @Input()
  nftID?: string | null;
  @Input()
  listingInfo?: ListedNfts200ResponseListingsInner | null;
  @Input()
  bidders?: BidderBids200ResponseBidsInner[] | null;
  @Input()
  loans?: Loans200ResponseLoansInner[] | null;
  @Input()
  nftMetadata?: Metadata | null;
  @Input()
  nftImage?: string | null;

  @Output()
  appSimulate: EventEmitter<BorrowRequest>;
  @Output()
  appSubmit: EventEmitter<BorrowRequest>;

  constructor() {
    this.appSimulate = new EventEmitter();
    this.appSubmit = new EventEmitter();
  }

  ngOnInit(): void {}

  onSimulate() {
    this.appSimulate.emit();
  }

  onSubmit() {
    this.appSubmit.emit();
  }
}

<div class="mx-auto max-w-screen-xl">
  <div class="text-xl breadcrumbs">
    <ul>
      <li routerLink="../../../.."><a>Top</a></li>
      <li routerLink="../../.."><a>Listed NFTs</a></li>
      <li>{{ classID }}</li>
      <li routerLink="..">
        <a>{{ nftID }}</a>
      </li>
    </ul>
  </div>
  <div class="text-xl breadcrumbs mb-4">
    <ul>
      <li></li>
      <li>Borrow Tokens</li>
    </ul>
  </div>

  <div class="card lg:card-side bg-base-100 shadow-xl mb-8">
    <figure class="aspect-square w-1/2 lg:w-1/4">
      <!-- img width setting not working -->
      <img
        src="{{ nftImage || 'assets/UnUniFi-logo.png' }}"
        alt="image of the NFT"
        class="object-cover"
      />
    </figure>
    <div class="card-body w-full lg:w-2/3">
      <div class="flex flex-row">
        <div class="badge badge-lg badge-primary">{{ listingInfo?.state }}</div>
      </div>
      <h2 class="card-title break-all">
        {{ nftMetadata?.name || classID + '/' + nftID }}
      </h2>
      <div class="overflow-x-auto">
        <table class="table w-full">
          <tbody>
            <tr>
              <td>Class ID</td>
              <td>{{ classID }}</td>
            </tr>
            <tr>
              <td>NFT ID</td>
              <td>{{ nftID }}</td>
            </tr>
            <tr>
              <td>Owner</td>
              <td>{{ listingInfo?.owner }}</td>
            </tr>
            <tr>
              <td>Bid Token</td>
              <td>{{ symbol }}</td>
            </tr>
            <tr>
              <td>Minimum deposit rate</td>
              <td>{{ listingInfo?.minimum_deposit_rate | percentage }}</td>
            </tr>
            <tr>
              <td>Started at</td>
              <td>{{ listingInfo?.started_at | date : 'yyyy-MM-dd a hh:mm:ss z' }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <div class="flex flex-col lg:flex-row mb-8">
    <div #chartCardRef class="card bg-base-100 shadow-xl w-full xl:w-2/3 mb-4 lg:mb-0 lg:mr-4">
      <div class="card-body">
        <h3 class="m-4 card-title">Deposits</h3>
        <google-chart
          *ngIf="chartData"
          [title]="chartTitle"
          [type]="chartType"
          [data]="chartData"
          [columns]="chartColumns"
          [options]="chartOptions"
        >
        </google-chart>
      </div>
    </div>

    <span class="flex-auto"></span>
    <div class="card bg-base-100 shadow-xl w-full xl:w-auto">
      <div class="card-body">
        <h3 class="m-4 card-title">Borrow</h3>
        <div class="btn-group">
          <label
            class="btn btn-outline w-1/2"
            [class.btn-active]="autoBorrow"
            (click)="onToggleAuto(true)"
          >
            Auto
          </label>
          <label
            class="btn btn-outline w-1/2"
            [class.btn-active]="!autoBorrow"
            (click)="onToggleAuto(false)"
          >
            Manual
          </label>
        </div>

        <form #autoFormRef="ngForm" (submit)="onSubmit()" *ngIf="autoBorrow">
          <div class="form-control">
            <span class="label">
              <span class="label-text">Enter borrow amount</span>
              <!-- The button to open modal -->
              <label for="modal-bid-price" class="label-text cursor-pointer">
                <mat-icon>help</mat-icon>
              </label>

              <!-- Put this part before </body> tag -->
              <input type="checkbox" id="modal-bid-price" class="modal-toggle" />
              <div class="modal modal-bottom sm:modal-middle">
                <div class="modal-box">
                  <h3 class="font-bold text-lg">What is the borrow amount?</h3>
                  <p class="py-4">
                    NFT listers can borrow tokens from the bid deposit. Borrowing will be made in
                    order of bids with lower interest rates. You must pay interest in addition to
                    the borrowed tokens by the repayment deadline. If you are unable to repay, the
                    NFT will be liquidated, but if there are other available bids, refinancing will
                    be carried out.
                  </p>
                  <div class="modal-action">
                    <label for="modal-bid-price" class="btn">Understood</label>
                  </div>
                </div>
              </div>
            </span>
            <label class="input-group">
              <span>
                <div class="mask mask-circle w-8 h-8">
                  <img src="{{ symbolImage }}" alt="Asset Symbol" />
                </div>
              </span>
              <input
                #borrowAmountRef="ngModel"
                required
                type="number"
                name="amount"
                [(ngModel)]="selectedBorrowAmount"
                [max]="borrowAmount || 0"
                [min]="0"
                [step]="1"
                class="input input-bordered w-full"
                [class]="{ 'input-error': borrowAmountRef.errors && borrowAmountRef.touched }"
                pattern="^[0-9]*\.?[0-9]{0,6}$"
                (change)="onChangeBorrowAmount()"
              />
              <span>{{ symbol }}</span>
            </label>
            <label class="label">
              <span class="label-text-alt">max borrowing amount:</span>
              <span class="label-text-alt"
                >{{ borrowAmount?.toString() | coinAmount }} {{ symbol }}
              </span>
            </label>
          </div>

          <div class="stats stats-vertical md:stats-horizontal justify-end my-4">
            <div class="stat flex flex-col items-end">
              <div class="stat-title">Average interest rate</div>
              <div class="stat-value">{{ averageInterestRate | percentage }}</div>
              <div class="stat-desc"></div>
            </div>
            <div class="stat flex flex-col items-end">
              <div class="stat-title">Shortest expiry date</div>
              <div class="stat-value">{{ shortestExpiryDate | date : 'yyyy-MM-dd' }}</div>
              <div class="stat-desc">{{ shortestExpiryDate | date : 'a hh:mm:ss z' }}</div>
            </div>
          </div>
          <div class="card-actions justify-end mt-4">
            <button
              class="btn btn-secondary w-full md:w-auto md:px-8"
              [disabled]="autoFormRef.invalid"
            >
              Borrow
            </button>
          </div>
        </form>

        <form #manualFormRef="ngForm" (submit)="onSubmit()" *ngIf="!autoBorrow">
          <ng-container *ngFor="let bid of selectedBids; let i = index">
            <div class="flex flex-row flex-wrap">
              <label class="input-group w-full mb-2">
                <span>{{ bid.address }}</span>
                <input
                  type="number"
                  [min]="0"
                  [step]="1"
                  [(ngModel)]="bid.amount"
                  name="bid{{ i }}"
                  class="input input-bordered w-full"
                />
                <span>{{ symbol }}</span>
                <label class="btn btn-outline btn-error" (click)="onClickDeleteBidder(i)">
                  <mat-icon>delete</mat-icon>
                </label>
              </label>
            </div>
          </ng-container>

          <div class="form-control">
            <label class="input-group mb-2 w-full sm:w-auto">
              <select
                [required]="selectedBids.length === 0"
                class="select select-bordered text-center w-auto sm:w-64"
                [(ngModel)]="selectedBidder"
                name="bidder"
              >
                <option [value]="undefined" disabled>
                  <span *ngIf="bidders?.length">Select a bidder</span>
                  <span *ngIf="!bidders?.length">No bidder</span>
                </option>
                <ng-container *ngFor="let b of bidders">
                  <option
                    [value]="b.id?.bidder"
                    *ngIf="!isAlreadySelectedBidder(b.id?.bidder || '')"
                  >
                    {{ b.id?.bidder }}
                  </option>
                </ng-container>
              </select>
              <button
                type="button"
                class="btn btn-outline btn-primary"
                (click)="onClickAddBidder()"
                [disabled]="!selectedBidder"
              >
                <mat-icon>add</mat-icon>
              </button>
            </label>
            <label class="label" *ngIf="selectedBidder">
              <span class="label-text-alt text-warning">Click + & enter amount!</span>
            </label>
          </div>

          <div class="card-actions justify-end mt-4">
            <button
              class="btn btn-secondary w-full md:w-auto md:px-8"
              [disabled]="manualFormRef.invalid"
            >
              Borrow
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>

  <div *ngIf="bidders?.length" class="card bg-base-100 shadow-xl">
    <div class="overflow-x-auto">
      <table class="table w-full">
        <thead>
          <tr>
            <th></th>
            <td>Interest</td>
            <td>Deposit</td>
            <td>Bid price</td>
            <td>Expiry</td>
            <td>Bidder</td>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let bidder of bidders; let i = index">
            <th>#{{ i + 1 }}</th>
            <td>{{ bidder.deposit_lending_rate | percentage }}</td>
            <td>{{ bidder.deposit_amount | coin | async }}</td>
            <td>{{ bidder.bid_amount | coin | async }}</td>
            <td>{{ bidder.bidding_period | date : 'yyyy-MM-dd a hh:mm z' }}</td>
            <td>{{ bidder.id?.bidder }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

// projects/nfloan/src/routes/nfts/[classId]/[tokenId]/borrow/+page.svelte
<div class="mx-auto max-w-screen-xl">
  <div class="text-xl breadcrumbs">
    <ul>
      <li routerLink="../../../.."><a>Top</a></li>
      <li routerLink="../../.."><a>Listed NFTs</a></li>
      <li>{ classID }</li>
      <li routerLink="..">
        <a>{ nftID }</a>
      </li>
    </ul>
  </div>
  <div class="text-xl breadcrumbs mb-4">
    <ul>
      <li></li>
      <li>Borrow from NFT Bids</li>
    </ul>
  </div>

  <div class="card lg:card-side bg-base-100 shadow-xl mb-8">
    <figure class="aspect-square w-1/2 lg:w-1/4">
      <!-- img width setting not working -->
      <img
        src="{ nftImage || 'assets/UnUniFi-logo.png' }"
        alt="image of the NFT"
        class="object-cover"
      />
    </figure>
    <div class="card-body w-full lg:w-2/3">
      <div class="flex flex-row">
        <div class="badge badge-lg badge-primary">{ listingInfo?.state }</div>
      </div>
      <h2 class="card-title break-all">
        { nftMetadata?.name }
      </h2>
      <div class="overflow-x-auto">
        <table class="table w-full">
          <tbody>
            <tr>
              <td>Class ID</td>
              <td>{ classID }</td>
            </tr>
            <tr>
              <td>NFT ID</td>
              <td>{ nftID }</td>
            </tr>
            <tr>
              <td>Owner</td>
              <td>{ listingInfo?.owner }</td>
            </tr>
            <tr>
              <td>Bid Token</td>
              <td>{ listingInfo?.bid_denom | coinDenom | async }</td>
            </tr>
            <tr>
              <td>Minimum deposit rate</td>
              <td>{ listingInfo?.min_deposit_rate | percent : '1.0-4' }</td>
            </tr>
            <tr>
              <td>Minimum bid Expiry date</td>
              <td>{ listingInfo?.min_bid_period | secondToDate } Days</td>
            </tr>
            <tr>
              <td>Listed</td>
              <td>{ listingInfo?.started_at | date : 'yyyy-MM-dd a hh:mm:ss z' }</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <div class="flex flex-col lg:flex-row mb-4">
    <div class="card bg-base-100 shadow-xl w-full xl:w-2/3 mb-4 lg:mr-4">
      <div class="card-body">
        <canvas #canvasChart></canvas>
      </div>
    </div>

    <!-- <div #chartCardRef class="card bg-base-100 shadow-xl w-full xl:w-2/3 mb-4 lg:mb-0 lg:mr-4">
      <div class="card-body">
        <h3 class="m-4 card-title">Deposits</h3>
        <google-chart
          *ngIf="chartData"
          [title]="chartTitle"
          [type]="chartType"
          [data]="chartData"
          [columns]="chartColumns"
          [options]="chartOptions"
        >
        </google-chart>
      </div>
    </div> -->

    <span class="flex-auto"></span>
    <div class="card bg-base-100 shadow-xl w-full xl:w-auto mb-4">
      <div class="card-body">
        <h3 class="m-4 card-title">Borrow</h3>
        <div class="btn-group">
          <label
            class="btn btn-outline w-1/2"
            [class.btn-active]="autoBorrow"
            (click)="onToggleAuto(true)"
          >
            Auto
          </label>
          <label
            class="btn btn-outline w-1/2"
            [class.btn-active]="!autoBorrow"
            (click)="onToggleAuto(false)"
          >
            Manual
          </label>
        </div>

        <form #autoFormRef="ngForm" (submit)="onSubmit()" *ngIf="autoBorrow">
          <div class="form-control">
            <span class="label">
              <span class="label-text">Enter borrow amount</span>
              <!-- The button to open modal -->
              <label for="modal-bid-price" class="label-text cursor-pointer">
                <span class="material-symbols-outlined">help</span>
              </label>

              <!-- Put this part before </body> tag -->
              <input type="checkbox" id="modal-bid-price" class="modal-toggle" />
              <div class="modal modal-bottom sm:modal-middle">
                <div class="modal-box">
                  <h3 class="font-bold text-lg">What is the borrow amount?</h3>
                  <p class="py-4">
                    NFT listers can borrow tokens from the bid deposit. Borrowing will be made in
                    order of bids with lower interest rates. You must pay interest in addition to
                    the borrowed tokens by the repayment deadline. If you are unable to repay, the
                    NFT will be liquidated, but if there are other available bids, refinancing will
                    be carried out.
                  </p>
                  <div class="modal-action">
                    <label for="modal-bid-price" class="btn">Okay</label>
                  </div>
                </div>
              </div>
            </span>
            <label class="input-group">
              <span>
                <div class="mask mask-circle w-8 h-8">
                  <img src={ symbolImage } alt="Asset Symbol" />
                </div>
              </span>
              <input
                #borrowAmountRef="ngModel"
                required
                type="number"
                name="amount"
                [(ngModel)]="selectedBorrowAmount"
                [max]="borrowAmount || 0"
                [min]="0"
                [step]="1"
                class="input input-bordered w-full"
                [class]="{ 'input-error': borrowAmountRef.errors && borrowAmountRef.touched }"
                pattern="^[0-9]*\.?[0-9]{0,6}$"
                (change)="onChangeBorrowAmount()"
              />
              <span>{ listingInfo?.bid_denom | coinDenom | async }</span>
            </label>
            <label class="label">
              <span class="label-text-alt">
                Max { borrowAmount } { listingInfo?.bid_denom | coinDenom | async }
              </span>
            </label>
          </div>

          <div class="stats stats-vertical md:stats-horizontal justify-end my-4">
            <div class="stat flex flex-col items-end">
              <div class="stat-title">Average interest rate</div>
              <div class="stat-value">{ averageInterestRate | percent : '1.0-4' }</div>
              <div class="stat-desc"></div>
            </div>
            <div class="stat flex flex-col items-end">
              <div class="stat-title">Shortest expiry date</div>
              <div class="stat-value">{ shortestExpiryDate | date : 'yyyy-MM-dd' }</div>
              <div class="stat-desc">{ shortestExpiryDate | date : 'a hh:mm:ss z' }</div>
            </div>
          </div>
          <div class="card-actions justify-end mt-4">
            <button
              class="btn btn-secondary w-full md:w-auto md:px-8"
              [disabled]="autoFormRef.invalid"
            >
              Borrow
            </button>
          </div>
        </form>

        <form #manualFormRef="ngForm" (submit)="onSubmit()" *ngIf="!autoBorrow">
          <div class="form-control">
            <ng-container *ngFor="let bid of selectedBids; let i = index">
              <div class="flex flex-row flex-wrap">
                <label class="label">
                  <span class="label-text font-mono">{ bid.address }</span>
                </label>
                <label class="input-group w-full mb-2">
                  <input
                    type="number"
                    [min]="0"
                    [step]="1"
                    [(ngModel)]="bid.amount"
                    name="bid{{ i }}"
                    class="input input-bordered w-full"
                  />
                  <span>{ listingInfo?.bid_denom | coinDenom | async }</span>
                  <label class="btn btn-outline btn-error" (click)="onClickDeleteBidder(i)">
                    <span class="material-symbols-outlined">delete</span>
                  </label>
                </label>
              </div>
            </ng-container>

            <label class="input-group mb-2 w-full sm:w-auto">
              <select
                [required]="selectedBids.length === 0"
                class="select select-bordered text-center w-auto sm:w-64"
                [(ngModel)]="selectedBidder"
                name="bidder"
              >
                <option [value]="undefined" disabled>
                  <span *ngIf="bids?.length">Select a bidder</span>
                  <span *ngIf="!bids?.length">No bidder</span>
                </option>
                <ng-container *ngFor="let b of bids">
                  <option
                    [value]="b.id?.bidder"
                    *ngIf="!isAlreadySelectedBidder(b.id?.bidder || '')"
                  >
                    { b.id?.bidder }
                  </option>
                </ng-container>
              </select>
              <button
                type="button"
                class="btn btn-outline btn-primary"
                (click)="onClickAddBidder()"
                [disabled]="!selectedBidder"
              >
                <span class="material-symbols-outlined">add</span>
              </button>
            </label>
            <label class="label" *ngIf="selectedBidder">
              <span class="label-text-alt text-warning">Click + & enter amount!</span>
            </label>
          </div>

          <div class="card-actions justify-end mt-4">
            <button
              class="btn btn-secondary w-full md:w-auto md:px-8"
              [disabled]="manualFormRef.invalid"
            >
              Borrow
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>

  <div *ngIf="bids?.length" class="card bg-base-100 shadow-xl">
    <div class="overflow-x-auto">
      <table class="table w-full">
        <thead>
          <tr>
            <th></th>
            <td>Interest</td>
            <td>Deposit</td>
            <td>Bid price</td>
            <td>Expiry</td>
            <td>Bidder</td>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let bid of bids; let i = index">
            <th>#{ i + 1 }</th>
            <td>{ bid.interest_rate | percent : '1.0-4' }</td>
            <td>{ bid.deposit | coin | async }</td>
            <td>{ bid.price | coin | async }</td>
            <td>{ bid.expiry | date : 'yyyy-MM-dd a hh:mm z' }</td>
            <td>{ bid.id?.bidder }</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
