// projects/kyc-provider/src/routes/auth/sign-up/+page.svelte
<script lang="ts">
	import { formula } from 'svelte-formula';
	import { authService } from '../../../models/state';
	import { GoogleAuthProvider } from 'firebase/auth';

	let processing = false;
	let email = '';
	let password = '';
	let passwordMatch = '';

	const validators = {};
	const formValidators = {
		passwordsMatch: (values: any) =>
			values.password === values.passwordMatch ? null : 'Passwords Must Match'
	};

	const { touched, validity, isFormValid } = formula({
		validators,
		formValidators
	});

	function signUpGoogle() {
		authService.signUp(new GoogleAuthProvider());
	}

	function signUpGithub() {}

	function signUpEmail() {}
</script>

<div class="card bg-base-100 shadow-xl">
	<div class="card-body">
		<h2 class="card-title">Sign Up</h2>
		<div class="flex flex-col">
			<button class="btn btn-neutral btn-outline w-full my-2" on:click={signUpGoogle}>
				Google
			</button>
			<button class="btn btn-neutral btn-outline w-full my-2" on:click={signUpGithub}>
				GitHub
			</button>
		</div>
		<form on:submit={signUpEmail}>
			<div class="form-control w-full">
				<span class="label">
					<span class="label-text">Email</span>
					<span class="label-text-alt" />
				</span>
				<input
					type="text"
					placeholder=""
					class="input input-bordered w-full"
					class:input-error={$touched.email && !$validity.email}
					required
					readonly={processing}
					autocomplete="email"
					bind:value={email}
					name="email"
				/>
				<span class="label">
					<span class="label-text" />
					<span class="label-text-alt" />
				</span>
			</div>
			<div class="form-control w-full">
				<span class="label">
					<span class="label-text">Password</span>
					<span class="label-text-alt" />
				</span>
				<input
					type="password"
					placeholder=""
					class="input input-bordered w-full"
					class:input-error={$touched.password && !$validity.password}
					required
					readonly={processing}
					autocomplete="new-password"
					bind:value={password}
					name="password"
				/>
				<span class="label">
					<span class="label-text" />
					<span class="label-text-alt" />
				</span>
			</div>
			<div class="form-control w-full">
				<span class="label">
					<span class="label-text">Confirm Password</span>
					<span class="label-text-alt" />
				</span>
				<input
					type="password"
					placeholder=""
					class="input input-bordered w-full"
					class:input-error={$touched.passwordMatch && !$validity.passwordMatch}
					required
					readonly={processing}
					autocomplete="new-password"
					bind:value={passwordMatch}
					name="passwordMatch"
				/>
				<span class="label">
					<span class="label-text" />
					<span class="label-text-alt" />
				</span>
			</div>
			<div class="card-actions justify-end">
				<button class="btn btn-primary" disabled={!$isFormValid || processing}> Sign Up </button>
			</div>
		</form>
	</div>
</div>

// projects/cefi/src/app/auth/sign-up/sign-up.component.ts
import { AuthService } from '../auth.service';
import { Component } from '@angular/core';
import { AuthProvider, GithubAuthProvider, GoogleAuthProvider } from '@angular/fire/auth';
import { Router } from '@angular/router';

@Component({
  selector: 'app-sign-up',
  templateUrl: './sign-up.component.html',
  styleUrls: ['./sign-up.component.css'],
})
export class SignUpComponent {
  email = '';
  password = '';
  idEntered = false;
  processing = false;

  constructor(private router: Router, private auth: AuthService) {}

  async signUp(provider: AuthProvider | { email: string; password: string }) {
    this.processing = true;

    try {
      await this.auth.signUp(provider);
      window.alert('Succeeded to sign up');
      this.router.navigate(['']);
    } catch (e) {
      window.alert('Failed to sign up');
    } finally {
      this.processing = false;
    }
  }

  async signUpGoogle() {
    await this.signUp(new GoogleAuthProvider());
  }

  async signUpGithub() {
    await this.signUp(new GithubAuthProvider());
  }

  signUpEmail(email: string, password: string) {
    this.signUp({ email, password });
  }
}

<div class="mx-auto px-4 max-w-screen-xl">
  <div class="card bg-base-100 shadow-xl">
    <div class="card-body">
      <h2 class="card-title">Sign Up</h2>
      <ng-container *ngIf="!idEntered">
        <form #idFormRef="ngForm" (submit)="submitUniqueName()">
          <div class="form-control w-full">
            <label class="label">
              <span class="label-text">Id</span>
              <span class="label-text-alt"></span>
            </label>
            <div class="input-group">
              <span>@</span>
              <input
                #idNgModelRef="ngModel"
                type="text"
                placeholder="'0'-'9', 'a'-'z', 'A'-'Z', '_' are available"
                class="input input-bordered w-full"
                [class]="{
                  'input-error': idNgModelRef.errors && idNgModelRef.touched
                }"
                required
                [readOnly]="processing"
                pattern="^[0-9a-zA-Z_]+$"
                autocomplete="nickname"
                [(ngModel)]="uniqueName"
                name="id"
              />
            </div>
            <label class="label">
              <span class="label-text"></span>
              <span class="label-text-alt"></span>
            </label>
          </div>
          <div class="card-actions justify-end">
            <button class="btn btn-primary" [disabled]="idFormRef.invalid || processing">
              Continue
            </button>
          </div>
        </form>
      </ng-container>
      <ng-container *ngIf="idEntered">
        <div class="flex flex-col">
          <button class="btn btn-neutral btn-outline w-full my-2" (click)="signUpGoogle()">
            Google
          </button>
          <button class="btn btn-neutral btn-outline w-full my-2" (click)="signUpGithub()">
            GitHub
          </button>
        </div>

        <form #formRef="ngForm" (submit)="signUpEmail(email, password)">
          <div class="form-control w-full">
            <label class="label">
              <span class="label-text">Email</span>
              <span class="label-text-alt"></span>
            </label>
            <input
              #emailNgModelRef="ngModel"
              type="text"
              placeholder=""
              class="input input-bordered w-full"
              [class]="{
                'input-error': emailNgModelRef.errors && emailNgModelRef.touched
              }"
              required
              pattern="^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$"
              [readOnly]="processing"
              autocomplete="email"
              [(ngModel)]="email"
              name="email"
            />
            <label class="label">
              <span class="label-text"></span>
              <span class="label-text-alt"></span>
            </label>
          </div>
          <div class="form-control w-full">
            <label class="label">
              <span class="label-text">Password</span>
              <span class="label-text-alt"></span>
            </label>
            <input
              #passwordNgModelRef="ngModel"
              type="password"
              placeholder=""
              class="input input-bordered w-full"
              [class]="{
                'input-error': passwordNgModelRef.errors && passwordNgModelRef.touched
              }"
              required
              [readOnly]="processing"
              autocomplete="new-password"
              [(ngModel)]="password"
              name="password"
            />
            <label class="label">
              <span class="label-text"></span>
              <span class="label-text-alt"></span>
            </label>
          </div>
          <div class="card-actions justify-end">
            <button class="btn btn-primary" [disabled]="formRef.invalid || processing">
              Sign Up
            </button>
          </div>
        </form>
      </ng-container>
    </div>
  </div>
</div>
