// projects/portal/src/app/views/nftbackedloan/borrowers/repay/repay.component.ts
import {
  Component,
  ElementRef,
  EventEmitter,
  Input,
  OnChanges,
  OnInit,
  Output,
  ViewChild,
} from '@angular/core';
import cosmosclient from '@cosmos-client/core';
import Chart from 'chart.js/auto';
import { getDenomExponent } from 'projects/portal/src/app/models/cosmos/bank.model';
import { NftPawnshopChartService } from 'projects/portal/src/app/models/nft-pawnshops/nft-pawnshop.chart.service';
import { RepayRequest } from 'projects/portal/src/app/models/nft-pawnshops/nft-pawnshop.model';
import { NftPawnshopService } from 'projects/portal/src/app/models/nft-pawnshops/nft-pawnshop.service';
import { Metadata } from 'projects/portal/src/app/models/nft/nft.model';
import ununificlient from 'ununifi-client';
import {
  NftBids200ResponseBidsInner,
  Liquidation200ResponseLiquidations,
  ListedNfts200ResponseListingsInnerListing,
} from 'ununifi-client/esm/openapi';

@Component({
  selector: 'view-repay',
  templateUrl: './repay.component.html',
  styleUrls: ['./repay.component.css'],
})
export class RepayComponent implements OnInit, OnChanges {
  @Input()
  classID?: string | null;
  @Input()
  nftID?: string | null;
  @Input()
  listingInfo?: ListedNfts200ResponseListingsInnerListing | null;
  @Input()
  symbol?: string | null;
  @Input()
  symbolMetadataMap?: {
    [symbol: string]: cosmosclient.proto.cosmos.bank.v1beta1.IMetadata;
  } | null;
  @Input()
  symbolImage?: string | null;
  @Input()
  bids?: NftBids200ResponseBidsInner[] | null;
  @Input()
  liquidation?: Liquidation200ResponseLiquidations | null;
  @Input()
  repayAmount?: number | null;
  @Input()
  nftMetadata?: Metadata | null;
  @Input()
  nftImage?: string | null;
  @Input()
  chartData?: (string | number)[][] | null;

  chart?: Chart<any>;
  contextChart?: CanvasRenderingContext2D;

  autoRepay = true;
  autoRepayBids: ununificlient.proto.ununifi.nftbackedloan.IBorrowBid[] = [];
  selectedBidder?: string;
  selectedBids: { address: string; amount: number }[] = [];

  @Output()
  appSubmit: EventEmitter<RepayRequest>;

  constructor(
    private readonly pawnshopChart: NftPawnshopChartService,
    private readonly nftPawnshopService: NftPawnshopService,
  ) {
    this.appSubmit = new EventEmitter();
  }

  @ViewChild('canvasChart') canvasChart?: ElementRef;

  ngOnInit(): void {}

  ngOnChanges(): void {
    this.onChangeRepayAmount();
    this.contextChart = this.canvasChart?.nativeElement.getContext('2d');
    if (this.chart) {
      this.chart.destroy();
    }
    if (this.contextChart && this.bids && this.listingInfo?.bid_denom) {
      this.chart = this.pawnshopChart.createExpiryDepositChart(
        this.contextChart,
        this.pawnshopChart.convertChartData(this.bids, this.listingInfo.bid_denom),
      );
    }
  }

  onToggleAuto(auto: boolean) {
    this.autoRepay = auto;
  }

  onChangeRepayAmount() {
    if (
      this.bids &&
      this.liquidation &&
      this.repayAmount &&
      this.symbol &&
      this.symbolMetadataMap
    ) {
      this.autoRepayBids = this.nftPawnshopService.autoRepayBids(
        this.bids,
        this.liquidation,
        this.repayAmount,
        this.symbol,
        this.symbolMetadataMap,
      );
      const exponent = getDenomExponent(this.listingInfo?.bid_denom);
      this.selectedBids = this.autoRepayBids.map((bid) => {
        return { address: bid.bidder!, amount: Number(bid.amount?.amount) / 10 ** exponent };
      });
    }
  }

  isAlreadySelectedBidder(bidderAddr: string) {
    return this.selectedBids.some((b) => b.address === bidderAddr);
  }

  onClickAddBidder() {
    if (!this.selectedBidder) {
      alert('Please select a bid.');
      return;
    }
    this.selectedBids.push({
      address: this.selectedBidder,
      amount: 0,
    });
    this.selectedBidder = undefined;
  }

  onClickDeleteBidder(index: number) {
    this.selectedBids.splice(index, 1);
  }

  onSubmit() {
    if (!this.classID || !this.nftID) {
      alert('Invalid NFT Info!');
      return;
    }
    if (this.autoRepay) {
      this.appSubmit.emit({
        classID: this.classID,
        nftID: this.nftID,
        repayBids: this.autoRepayBids,
      });
    } else {
      if (!this.symbol || !this.symbolMetadataMap) {
        alert('Invalid Token!');
        return;
      }
      const repayBids = this.nftPawnshopService.convertBorrowBids(
        this.selectedBids,
        this.symbol,
        this.symbolMetadataMap,
      );
      this.appSubmit.emit({
        classID: this.classID,
        nftID: this.nftID,
        repayBids,
      });
    }
  }
}

<div class="mx-auto max-w-screen-xl">
  <div class="text-xl breadcrumbs">
    <ul>
      <li routerLink="../../../.."><a>Top</a></li>
      <li routerLink="../../.."><a>Listed NFTs</a></li>
      <li>{{ classID }}</li>
      <li routerLink="..">
        <a>{{ nftID }}</a>
      </li>
    </ul>
  </div>
  <div class="text-xl breadcrumbs mb-4">
    <ul>
      <li></li>
      <li>Repay to NFT Bids</li>
    </ul>
  </div>
  <div class="card lg:card-side bg-base-100 shadow-xl mb-8">
    <figure class="aspect-square w-1/2 lg:w-1/4">
      <!-- img width setting not working -->
      <img
        src="{{ nftImage || 'assets/UnUniFi-logo.png' }}"
        alt="image of the NFT"
        class="object-cover"
      />
    </figure>
    <div class="card-body w-full lg:w-2/3">
      <div class="flex flex-row">
        <div class="badge badge-lg badge-primary">{{ listingInfo?.state }}</div>
      </div>
      <h2 class="card-title break-all">
        {{ nftMetadata?.name }}
      </h2>
      <div class="overflow-x-auto">
        <table class="table w-full">
          <tbody>
            <tr>
              <td>Class ID</td>
              <td>{{ classID }}</td>
            </tr>
            <tr>
              <td>NFT ID</td>
              <td>{{ nftID }}</td>
            </tr>
            <tr>
              <td>Owner</td>
              <td>{{ listingInfo?.owner }}</td>
            </tr>
            <tr>
              <td>Bid Token</td>
              <td>{{ listingInfo?.bid_denom | coinDenom | async }}</td>
            </tr>
            <tr>
              <td>Minimum deposit rate</td>
              <td>{{ listingInfo?.min_deposit_rate | percent : '1.0-4' }}</td>
            </tr>
            <tr>
              <td>Minimum bid Expiry date</td>
              <td>{{ listingInfo?.min_bid_period | secondToDate }} Days</td>
            </tr>
            <tr>
              <td>Listed</td>
              <td>{{ listingInfo?.started_at | date : 'yyyy-MM-dd a hh:mm:ss z' }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <div class="flex flex-col lg:flex-row mb-4">
    <div class="card bg-base-100 shadow-xl w-full xl:w-2/3 mb-4 lg:mr-4">
      <div class="card-body">
        <canvas #canvasChart></canvas>
      </div>
    </div>
    <!-- <div #chartCardRef class="card bg-base-100 shadow-xl w-full lg:w-2/3 mb-4 lg:mb-0 lg:mr-4">
      <h3 class="m-4 card-title">Borrowing</h3>
      <google-chart
        *ngIf="chartData"
        [title]="chartTitle"
        [type]="chartType"
        [data]="chartData"
        [columns]="chartColumns"
        [options]="chartOptions"
      >
      </google-chart>
    </div>  -->

    <span class="flex-auto"></span>
    <div class="card bg-base-100 shadow-xl w-full xl:w-auto mb-4">
      <div class="card-body">
        <h3 class="m-4 card-title">Repay</h3>
        <div class="btn-group">
          <label
            class="btn btn-outline w-1/2"
            [class.btn-active]="autoRepay"
            (click)="onToggleAuto(true)"
          >
            Auto
          </label>
          <label
            class="btn btn-outline w-1/2"
            [class.btn-active]="!autoRepay"
            (click)="onToggleAuto(false)"
          >
            Manual
          </label>
        </div>

        <form #autoFormRef="ngForm" (submit)="onSubmit()" *ngIf="autoRepay">
          <div class="form-control">
            <span class="label">
              <span class="label-text">Enter repay amount</span>
              <!-- The button to open modal -->
              <label for="modal-bid-price" class="label-text cursor-pointer">
                <span class="material-symbols-outlined">help</span>
              </label>

              <!-- Put this part before </body> tag -->
              <input type="checkbox" id="modal-bid-price" class="modal-toggle" />
              <div class="modal modal-bottom sm:modal-middle">
                <div class="modal-box">
                  <h3 class="font-bold text-lg">What is the repay amount?</h3>
                  <p class="py-4">
                    You must repay the borrowed tokens and interest by the repayment deadline. If
                    you are unable to repay, the NFT will be liquidated, but if there are other
                    available bids, refinancing will be carried out. Repayment will be made starting
                    with the highest interest rates.
                  </p>
                  <div class="modal-action">
                    <label for="modal-bid-price" class="btn">Understood</label>
                  </div>
                </div>
              </div>
            </span>
            <label class="input-group">
              <span>
                <div class="mask mask-circle w-8 h-8">
                  <img src="{{ symbolImage }}" alt="Asset Symbol" />
                </div>
              </span>
              <input
                #repayAmountNgModelRef="ngModel"
                required
                type="number"
                name="amount"
                [(ngModel)]="repayAmount"
                [min]="0"
                [step]="1"
                class="input input-bordered w-full"
                [class]="{
                  'input-error': repayAmountNgModelRef.errors && repayAmountNgModelRef.touched
                }"
                pattern="^[0-9]*\.?[0-9]{0,6}$"
                (change)="onChangeRepayAmount()"
              />
              <span>{{ listingInfo?.bid_denom | coinDenom | async }}</span>
            </label>
          </div>

          <div class="card-actions justify-end mt-4">
            <button
              class="btn btn-primary w-full md:w-auto md:px-8"
              [disabled]="autoFormRef.invalid"
            >
              Repay
            </button>
          </div>
        </form>

        <form #manualFormRef="ngForm" (submit)="onSubmit()" *ngIf="!autoRepay">
          <div class="form-control">
            <ng-container *ngFor="let bid of selectedBids; let i = index">
              <div class="flex flex-row flex-wrap">
                <label class="label">
                  <span class="label-text font-mono">{{ bid.address }}</span>
                </label>
                <label class="input-group w-full mb-2">
                  <input
                    type="number"
                    [min]="0"
                    [step]="1"
                    [(ngModel)]="bid.amount"
                    name="bid{{ i }}"
                    class="input input-bordered w-full"
                  />
                  <span>{{ listingInfo?.bid_denom | coinDenom | async }}</span>
                  <label class="btn btn-outline btn-error" (click)="onClickDeleteBidder(i)">
                    <span class="material-symbols-outlined">delete</span>
                  </label>
                </label>
              </div>
            </ng-container>

            <label class="input-group mb-2 w-full sm:w-auto">
              <select
                [required]="selectedBids.length === 0"
                class="select select-bordered text-center w-auto sm:w-64"
                [(ngModel)]="selectedBidder"
                name="bidder"
              >
                <option [value]="undefined" disabled>
                  <span *ngIf="bids?.length">Select a bidder</span>
                  <span *ngIf="!bids?.length">No bidder</span>
                </option>
                <ng-container *ngFor="let b of bids">
                  <option
                    [value]="b.id?.bidder"
                    *ngIf="!isAlreadySelectedBidder(b.id?.bidder || '')"
                  >
                    {{ b.id?.bidder }}
                  </option>
                </ng-container>
              </select>
              <button
                type="button"
                class="btn btn-outline btn-primary"
                (click)="onClickAddBidder()"
                [disabled]="!selectedBidder"
              >
                <span class="material-symbols-outlined">add</span>
              </button>
            </label>
            <label class="label" *ngIf="selectedBidder">
              <span class="label-text-alt text-warning">Click + & enter amount!</span>
            </label>
          </div>

          <div class="card-actions justify-end mt-4">
            <button
              class="btn btn-primary w-full md:w-auto md:px-8"
              [disabled]="manualFormRef.invalid"
            >
              Repay
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>

  <div *ngIf="bids?.length" class="card bg-base-100 shadow-xl">
    <div class="overflow-x-auto">
      <table class="table w-full">
        <thead>
          <tr>
            <th></th>
            <td>Interest</td>
            <td>Borrowing Amount</td>
            <td>Bid price</td>
            <td>Expiry</td>
            <td>Bidder</td>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let bid of bids; let i = index">
            <th>#{{ i + 1 }}</th>
            <td>{{ bid.interest_rate | percent : '1.0-4' }}</td>
            <td>{{ bid.loan?.amount | coin | async }}</td>
            <td>{{ bid.price | coin | async }}</td>
            <td>{{ bid.expiry | date : 'yyyy-MM-dd a hh:mm z' }}</td>
            <td>{{ bid.id?.bidder }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

// projects/nfloan/src/routes/nfts/[classId]/[tokenId]/repay/+page.svelte
<div class="mx-auto max-w-screen-xl">
  <div class="text-xl breadcrumbs">
    <ul>
      <li><a href="../../../..">Top</a></li>
      <li><a href="../../..">Listed NFTs</a></li>
      <li>{ classID }</li>
      <li>
        <a href="..">{ nftID }</a>
      </li>
    </ul>
  </div>
  <div class="text-xl breadcrumbs mb-4">
    <ul>
      <li></li>
      <li>Repay to NFT Bids</li>
    </ul>
  </div>
  <div class="card lg:card-side bg-base-100 shadow-xl mb-8">
    <figure class="aspect-square w-1/2 lg:w-1/4">
      <!-- img width setting not working -->
      <img
        src="{ nftImage || 'assets/UnUniFi-logo.png' }"
        alt="image of the NFT"
        class="object-cover"
      />
    </figure>
    <div class="card-body w-full lg:w-2/3">
      <div class="flex flex-row">
        <div class="badge badge-lg badge-primary">{ listingInfo?.state }</div>
      </div>
      <h2 class="card-title break-all">
        { nftMetadata?.name }
      </h2>
      <div class="overflow-x-auto">
        <table class="table w-full">
          <tbody>
            <tr>
              <td>Class ID</td>
              <td>{ classID }</td>
            </tr>
            <tr>
              <td>NFT ID</td>
              <td>{ nftID }</td>
            </tr>
            <tr>
              <td>Owner</td>
              <td>{ listingInfo?.owner }</td>
            </tr>
            <tr>
              <td>Bid Token</td>
              <td>{ listingInfo?.bid_denom | coinDenom | async }</td>
            </tr>
            <tr>
              <td>Minimum deposit rate</td>
              <td>{ listingInfo?.min_deposit_rate | percent : '1.0-4' }</td>
            </tr>
            <tr>
              <td>Minimum bid Expiry date</td>
              <td>{ listingInfo?.min_bid_period | secondToDate } Days</td>
            </tr>
            <tr>
              <td>Listed</td>
              <td>{ listingInfo?.started_at | date : 'yyyy-MM-dd a hh:mm:ss z' }</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <div class="flex flex-col lg:flex-row mb-4">
    <div class="card bg-base-100 shadow-xl w-full xl:w-2/3 mb-4 lg:mr-4">
      <div class="card-body">
        <canvas #canvasChart></canvas>
      </div>
    </div>
    <!-- <div #chartCardRef class="card bg-base-100 shadow-xl w-full lg:w-2/3 mb-4 lg:mb-0 lg:mr-4">
      <h3 class="m-4 card-title">Borrowing</h3>
      <google-chart
        *ngIf="chartData"
        [title]="chartTitle"
        [type]="chartType"
        [data]="chartData"
        [columns]="chartColumns"
        [options]="chartOptions"
      >
      </google-chart>
    </div>  -->

    <span class="flex-auto"></span>
    <div class="card bg-base-100 shadow-xl w-full xl:w-auto mb-4">
      <div class="card-body">
        <h3 class="m-4 card-title">Repay</h3>
        <div class="btn-group">
          <label
            class="btn btn-outline w-1/2"
            [class.btn-active]="autoRepay"
            (click)="onToggleAuto(true)"
          >
            Auto
          </label>
          <label
            class="btn btn-outline w-1/2"
            [class.btn-active]="!autoRepay"
            (click)="onToggleAuto(false)"
          >
            Manual
          </label>
        </div>

        <form #autoFormRef="ngForm" (submit)="onSubmit()" *ngIf="autoRepay">
          <div class="form-control">
            <span class="label">
              <span class="label-text">Enter repay amount</span>
              <!-- The button to open modal -->
              <label for="modal-bid-price" class="label-text cursor-pointer">
                <span class="material-symbols-outlined">help</span>
              </label>

              <!-- Put this part before </body> tag -->
              <input type="checkbox" id="modal-bid-price" class="modal-toggle" />
              <div class="modal modal-bottom sm:modal-middle">
                <div class="modal-box">
                  <h3 class="font-bold text-lg">What is the repay amount?</h3>
                  <p class="py-4">
                    You must repay the borrowed tokens and interest by the repayment deadline. If
                    you are unable to repay, the NFT will be liquidated, but if there are other
                    available bids, refinancing will be carried out. Repayment will be made starting
                    with the highest interest rates.
                  </p>
                  <div class="modal-action">
                    <label for="modal-bid-price" class="btn">Okay</label>
                  </div>
                </div>
              </div>
            </span>
            <label class="input-group">
              <span>
                <div class="mask mask-circle w-8 h-8">
                  <img src="{{ symbolImage }}" alt="Asset Symbol" />
                </div>
              </span>
              <input
                #repayAmountNgModelRef="ngModel"
                required
                type="number"
                name="amount"
                [(ngModel)]="repayAmount"
                [min]="0"
                [step]="1"
                class="input input-bordered w-full"
                [class]="{
                  'input-error': repayAmountNgModelRef.errors && repayAmountNgModelRef.touched
                }"
                pattern="^[0-9]*\.?[0-9]{0,6}$"
                (change)="onChangeRepayAmount()"
              />
              <span>{ listingInfo?.bid_denom | coinDenom | async }</span>
            </label>
          </div>

          <div class="card-actions justify-end mt-4">
            <button
              class="btn btn-primary w-full md:w-auto md:px-8"
              [disabled]="autoFormRef.invalid"
            >
              Repay
            </button>
          </div>
        </form>

        <form #manualFormRef="ngForm" (submit)="onSubmit()" *ngIf="!autoRepay">
          <div class="form-control">
            <ng-container *ngFor="let bid of selectedBids; let i = index">
              <div class="flex flex-row flex-wrap">
                <label class="label">
                  <span class="label-text font-mono">{{ bid.address }}</span>
                </label>
                <label class="input-group w-full mb-2">
                  <input
                    type="number"
                    [min]="0"
                    [step]="1"
                    [(ngModel)]="bid.amount"
                    name="bid{{ i }}"
                    class="input input-bordered w-full"
                  />
                  <span>{ listingInfo?.bid_denom | coinDenom | async }</span>
                  <label class="btn btn-outline btn-error" (click)="onClickDeleteBidder(i)">
                    <span class="material-symbols-outlined">delete</span>
                  </label>
                </label>
              </div>
            </ng-container>

            <label class="input-group mb-2 w-full sm:w-auto">
              <select
                [required]="selectedBids.length === 0"
                class="select select-bordered text-center w-auto sm:w-64"
                [(ngModel)]="selectedBidder"
                name="bidder"
              >
                <option [value]="undefined" disabled>
                  <span *ngIf="bids?.length">Select a bidder</span>
                  <span *ngIf="!bids?.length">No bidder</span>
                </option>
                <ng-container *ngFor="let b of bids">
                  <option
                    [value]="b.id?.bidder"
                    *ngIf="!isAlreadySelectedBidder(b.id?.bidder || '')"
                  >
                    { b.id?.bidder }
                  </option>
                </ng-container>
              </select>
              <button
                type="button"
                class="btn btn-outline btn-primary"
                (click)="onClickAddBidder()"
                [disabled]="!selectedBidder"
              >
                <span class="material-symbols-outlined">add</span>
              </button>
            </label>
            <label class="label" *ngIf="selectedBidder">
              <span class="label-text-alt text-warning">Click + & enter amount!</span>
            </label>
          </div>

          <div class="card-actions justify-end mt-4">
            <button
              class="btn btn-primary w-full md:w-auto md:px-8"
              [disabled]="manualFormRef.invalid"
            >
              Repay
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>

  <div *ngIf="bids?.length" class="card bg-base-100 shadow-xl">
    <div class="overflow-x-auto">
      <table class="table w-full">
        <thead>
          <tr>
            <th></th>
            <td>Interest</td>
            <td>Borrowing Amount</td>
            <td>Bid price</td>
            <td>Expiry</td>
            <td>Bidder</td>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let bid of bids; let i = index">
            <th>#{ i + 1 }</th>
            <td>{ bid.interest_rate | percent : '1.0-4' }</td>
            <td>{ bid.loan?.amount | coin | async }</td>
            <td>{ bid.price | coin | async }</td>
            <td>{ bid.expiry | date : 'yyyy-MM-dd a hh:mm z' }</td>
            <td>{ bid.id?.bidder }</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
